/** Main-process-only OAuth 2.0 PKCE primitives. Never expose this material over IPC. */

import { createHash, randomBytes, timingSafeEqual } from 'node:crypto'

const PKCE_VERIFIER_BYTES = 48
const OAUTH_STATE_BYTES = 32
const BASE64URL_RE = /^[A-Za-z0-9_-]+$/

export type McpOAuthPkceMaterial = Readonly<{
  /** RFC 7636 verifier. Keep main-process-only until token exchange completes. */
  verifier: string
  /** S256 code challenge safe to place in an authorization request. */
  challenge: string
  method: 'S256'
  /** Opaque CSRF/callback correlation nonce. Keep main-process-only. */
  state: string
}>

/** Creates high-entropy PKCE and callback-state material for one authorization attempt. */
export function createMcpOAuthPkceMaterial(): McpOAuthPkceMaterial {
  const verifier = randomBase64Url(PKCE_VERIFIER_BYTES)
  const state = randomBase64Url(OAUTH_STATE_BYTES)
  return Object.freeze({
    verifier,
    challenge: createHash('sha256').update(verifier, 'ascii').digest('base64url'),
    method: 'S256' as const,
    state
  })
}

/** Strictly validates the opaque base64url state format generated by this module. */
export function isValidMcpOAuthState(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    value.length >= 43 &&
    value.length <= 128 &&
    BASE64URL_RE.test(value)
  )
}

/** RFC 7636 verifier syntax with the length range required by the specification. */
export function isValidMcpOAuthPkceVerifier(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    value.length >= 43 &&
    value.length <= 128 &&
    /^[A-Za-z0-9\-._~]+$/.test(value)
  )
}

/**
 * Fixed-length, timing-safe equality for callback state comparison. Invalid input
 * is rejected without attempting a comparison.
 */
export function mcpOAuthStateEquals(left: string, right: string): boolean {
  if (!isValidMcpOAuthState(left) || !isValidMcpOAuthState(right) || left.length !== right.length) {
    return false
  }
  return timingSafeEqual(Buffer.from(left, 'ascii'), Buffer.from(right, 'ascii'))
}

function randomBase64Url(bytes: number): string {
  return randomBytes(bytes).toString('base64url')
}
